title: Renan Taranto
tagline: Software Development
description: Software architecture, engineering and design.
url: https://www.renantaranto.com
author: Renan Taranto
social:
  name: Renan Taranto
  links:
    - https://twitter.com/RenanTaranto
    - https://www.linkedin.com/in/renan-taranto
    - https://github.com/renan-taranto
twitter:
  username: RenanTaranto
  card: summary
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/renan-taranto.jpeg

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
