# Site settings
title: Renan Taranto
header-img: img/home-bg.jpg
email: renantaranto@gmail.com
copyright_name: Renan Taranto
description: "Blog aboute software development. Focused on architecture and object oriented design"
url: "https://www.renantaranto.com"
github_username: renan-taranto
facebook_username: renan.taranto
email_username: renantaranto@gmail.com

google_tracking_id: UA-102354854-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
