# Front Matter Defaults
defaults:
  - scope:
      path: "index.md"
    values:
      navigation: "home-navigation.html"
      header: "home-header.html"
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "prose"
  - scope:
      path: ""
    values:
      layout: "default"
      navigation: "navigation.html"
      header: "header.html"
      image: /assets/images/renan-taranto.jpeg

# Sass
sass:
  style: compressed
  sourcemap: never

# jekyll-seo-tag
title: Renan Taranto
tagline: Software Architect
description: Software Architect
url: https://www.renantaranto.com
author: Renan Taranto
social:
  name: Renan Taranto
  links:
    - https://www.linkedin.com/in/renan-taranto
    - https://github.com/renan-taranto
twitter:
  username: RenanTaranto
  card: summary

# Google Analytics
analytics_tracking_id: UA-102354854-1

# jekyll-polyglot
languages: ["en_US", "pt_BR"]
default_lang: "en_US"
exclude_from_localization: ["assets"]
parallel_localization: true

# User added
social_links:
  linkedin: https://www.linkedin.com/in/renan-taranto
  github: https://github.com/renan-taranto
proposal:
  en_US: Software Architecture and Quality
  pt_BR: Arquitetura e Qualidade de Software

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
