title: Renan Taranto
tagline: Software Development
description: Software architecture, engineering and code design.
url: https://www.renantaranto.com
author: Renan Taranto
social:
  name: Renan Taranto
  links:
    - https://twitter.com/RenanTaranto
    - https://www.linkedin.com/in/renan-taranto
    - https://github.com/renan-taranto
twitter:
  username: RenanTaranto
  card: summary
defaults:
  - scope:
      path: "index.md"
    values:
      navigation: "index-navigation.html"
      header: "index-header.html"
      layout: "index"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "prose"
  - scope:
      path: ""
    values:
      layout: "default"
      navigation: "navigation.html"
      header: "header.html"
      image: /assets/images/renan-taranto.jpeg

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
