title: Renan Taranto
tagline: Software Development
description: Software architecture, engineering and design
proposal:
  en_US: Software development advisory
  pt_BR: Assessoria em desenvolvimento de software
focus:
  en_US: Software quality, engineering and architecture
  pt_BR: Engenharia, arquitetura e qualidade de software
url: https://www.renantaranto.com
author: Renan Taranto
social:
  name: Renan Taranto
  links:
    - https://twitter.com/RenanTaranto
    - https://www.linkedin.com/in/renan-taranto
    - https://github.com/renan-taranto
twitter:
  username: RenanTaranto
  card: summary

analytics_tracking_id: UA-102354854-1

defaults:
  - scope:
      path: "index.md"
    values:
      navigation: "home-navigation.html"
      header: "home-header.html"
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "prose"
  - scope:
      path: ""
    values:
      layout: "default"
      navigation: "navigation.html"
      header: "header.html"
      image: /assets/images/renan-taranto.jpeg

sass:
  style: compressed
  sourcemap: never

languages: ["en_US", "pt_BR"]
default_lang: "en_US"
exclude_from_localization: ["assets"]
parallel_localization: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
